"""remove unique constraint from fullname

Revision ID: bb0a1f821895
Revises: 18ec18d5b3bd
Create Date: 2026-07-08 18:15:48.436318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb0a1f821895'
down_revision: Union[str, Sequence[str], None] = '18ec18d5b3bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_fullname_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_fullname_key'), 'users', ['fullname'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
